# -*- coding: utf-8 -*-
"""skema_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxs6ennIijetj1BSKzbRWThs_s7piYph
"""

install streamlit as st

st.write('Hello World')