# -*- coding: utf-8 -*-
"""skema_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxs6ennIijetj1BSKzbRWThs_s7piYph
"""

import streamlit as st

st.write('Hello World')

# Verbose version
my_db.connect(username=st.secrets.db_credentials.username, password=st.secrets.db_credentials.password)

# Far more compact version!
my_db.connect(**st.secrets.db_credentials)
